insert into public.assessment_questions (id, question_text, display_order) values
  ('q1', 'I enjoy explaining ideas until they finally click for someone.', 1),
  ('q2', 'I naturally notice practical needs and want to help.', 2),
  ('q3', 'People often come to me when they need encouragement.', 3),
  ('q4', 'I am comfortable taking responsibility when a group needs direction.', 4),
  ('q5', 'I feel deeply affected when I see someone struggling.', 5),
  ('q6', 'I enjoy using my resources to help others succeed.', 6),
  ('q7', 'I am willing to speak up about what I believe is right, even when it is uncomfortable.', 7),
  ('q8', 'I like turning complicated information into a simple path forward.', 8),
  ('q9', 'I would rather help behind the scenes than be recognized publicly.', 9),
  ('q10', 'When someone feels stuck, I look for a practical next step they can take.', 10),
  ('q11', 'I can usually sense when a group is drifting from its purpose.', 11),
  ('q12', 'I pay attention to whether vulnerable people are being cared for.', 12),
  ('q13', 'I am energized by organizing people around a shared goal.', 13),
  ('q14', 'I think carefully about how money, time, and resources can create good.', 14),
  ('q15', 'I lose interest when conversations become too theoretical.', 15),
  ('q16', 'I enjoy creating systems that make service easier for everyone.', 16),
  ('q17', 'I am drawn to people others might overlook.', 17),
  ('q18', 'I often help people name what they are learning.', 18),
  ('q19', 'I give candid feedback when I believe silence would be unhelpful.', 19),
  ('q20', 'I like celebrating progress and helping people keep going.', 20),
  ('q21', 'I prefer not to make decisions that affect a group.', 21),
  ('q22', 'I find joy in giving quietly when I know it meets a real need.', 22),
  ('q23', 'I can stay patient with someone who needs extra time to understand.', 23),
  ('q24', 'I often volunteer for details others do not want to handle.', 24),
  ('q25', 'I am bothered when people use spiritual language to avoid responsibility.', 25),
  ('q26', 'I like helping a team choose priorities and move forward.', 26),
  ('q27', 'I notice who is discouraged before others do.', 27),
  ('q28', 'I am reluctant to share resources unless I know I will benefit.', 28),
  ('q29', 'I am energized by hospitality, logistics, or hands-on support.', 29),
  ('q30', 'I often connect present choices to long-term consequences.', 30),
  ('q31', 'I enjoy mentoring someone through repeated conversations.', 31),
  ('q32', 'I feel protective toward people who are grieving or isolated.', 32),
  ('q33', 'I can explain why a belief or practice matters, not just what it is.', 33),
  ('q34', 'I tend to wait for someone else to make a plan.', 34),
  ('q35', 'I think generosity should be thoughtful, not impulsive.', 35),
  ('q36', 'I am quick to step into practical tasks when pressure rises.', 36),
  ('q37', 'I can sit with painful stories without rushing people through them.', 37),
  ('q38', 'I enjoy building training, guides, lessons, or frameworks.', 38),
  ('q39', 'I feel responsible to challenge harmful patterns.', 39),
  ('q40', 'I naturally think about how to equip other people, not just complete the task.', 40),
  ('q41', 'I like connecting people with resources they did not know were available.', 41),
  ('q42', 'I usually notice morale and energy in a room.', 42),
  ('q43', 'I become impatient when serving requires repetitive unseen work.', 43),
  ('q44', 'I am willing to ask direct questions when something feels unclear or untrue.', 44),
  ('q45', 'I enjoy helping people imagine a better future.', 45),
  ('q46', 'I think carefully about fairness and stewardship before committing resources.', 46),
  ('q47', 'I can help a group turn a broad idea into next actions.', 47),
  ('q48', 'I am drawn to work where compassion is central, even if it is emotionally demanding.', 48),
  ('q49', 'I enjoy answering follow-up questions and helping someone go deeper.', 49),
  ('q50', 'I prefer harmony so much that I rarely say what I really think.', 50),
  ('q51', 'I enjoy making others feel practically supported and cared for.', 51),
  ('q52', 'I often help people regain courage after disappointment.', 52),
  ('q53', 'I notice capable people and want to invest in their growth.', 53),
  ('q54', 'I am comfortable simplifying choices so people can act.', 54),
  ('q55', 'I feel joy when someone else succeeds because of something I contributed.', 55),
  ('q56', 'I want my work to connect truth, service, compassion, and action.', 56)
on conflict (id) do update set question_text = excluded.question_text, display_order = excluded.display_order, active = true;

insert into public.question_gift_weights (question_id, gift_id, weight, reverse_scored) values
  ('q1', 'teaching', 1.00, false),
  ('q1', 'encouragement', 0.25, false),
  ('q2', 'serving', 1.00, false),
  ('q2', 'mercy', 0.25, false),
  ('q3', 'encouragement', 1.00, false),
  ('q3', 'mercy', 0.30, false),
  ('q4', 'leadership', 1.00, false),
  ('q5', 'mercy', 1.00, false),
  ('q6', 'giving', 1.00, false),
  ('q6', 'serving', 0.25, false),
  ('q7', 'prophecy', 1.00, false),
  ('q7', 'leadership', 0.20, false),
  ('q8', 'teaching', 0.80, false),
  ('q8', 'leadership', 0.40, false),
  ('q9', 'serving', 0.90, false),
  ('q9', 'giving', 0.30, false),
  ('q10', 'encouragement', 0.80, false),
  ('q10', 'teaching', 0.25, false),
  ('q11', 'prophecy', 0.80, false),
  ('q11', 'leadership', 0.35, false),
  ('q12', 'mercy', 0.85, false),
  ('q12', 'prophecy', 0.25, false),
  ('q13', 'leadership', 1.00, false),
  ('q14', 'giving', 0.90, false),
  ('q14', 'leadership', 0.25, false),
  ('q15', 'teaching', 0.70, true),
  ('q16', 'serving', 0.65, false),
  ('q16', 'leadership', 0.55, false),
  ('q17', 'mercy', 0.90, false),
  ('q17', 'serving', 0.30, false),
  ('q18', 'teaching', 0.75, false),
  ('q18', 'encouragement', 0.45, false),
  ('q19', 'prophecy', 0.90, false),
  ('q20', 'encouragement', 0.95, false),
  ('q21', 'leadership', 0.80, true),
  ('q22', 'giving', 1.00, false),
  ('q22', 'mercy', 0.25, false),
  ('q23', 'teaching', 0.65, false),
  ('q23', 'mercy', 0.35, false),
  ('q24', 'serving', 0.90, false),
  ('q25', 'prophecy', 0.85, false),
  ('q25', 'teaching', 0.20, false),
  ('q26', 'leadership', 0.90, false),
  ('q26', 'encouragement', 0.25, false),
  ('q27', 'encouragement', 0.65, false),
  ('q27', 'mercy', 0.55, false),
  ('q28', 'giving', 0.90, true),
  ('q29', 'serving', 0.95, false),
  ('q30', 'prophecy', 0.55, false),
  ('q30', 'leadership', 0.45, false),
  ('q30', 'teaching', 0.20, false),
  ('q31', 'encouragement', 0.65, false),
  ('q31', 'teaching', 0.55, false),
  ('q32', 'mercy', 0.95, false),
  ('q33', 'teaching', 0.80, false),
  ('q33', 'prophecy', 0.35, false),
  ('q34', 'leadership', 0.75, true),
  ('q35', 'giving', 0.75, false),
  ('q35', 'teaching', 0.20, false),
  ('q36', 'serving', 0.80, false),
  ('q36', 'leadership', 0.30, false),
  ('q37', 'mercy', 0.90, false),
  ('q38', 'teaching', 1.00, false),
  ('q39', 'prophecy', 0.85, false),
  ('q39', 'mercy', 0.20, false),
  ('q40', 'leadership', 0.45, false),
  ('q40', 'teaching', 0.45, false),
  ('q40', 'encouragement', 0.35, false),
  ('q41', 'giving', 0.65, false),
  ('q41', 'encouragement', 0.35, false),
  ('q42', 'encouragement', 0.55, false),
  ('q42', 'leadership', 0.35, false),
  ('q42', 'mercy', 0.25, false),
  ('q43', 'serving', 0.80, true),
  ('q44', 'prophecy', 0.80, false),
  ('q44', 'teaching', 0.25, false),
  ('q45', 'encouragement', 0.65, false),
  ('q45', 'leadership', 0.35, false),
  ('q46', 'giving', 0.75, false),
  ('q46', 'prophecy', 0.25, false),
  ('q47', 'leadership', 0.85, false),
  ('q47', 'serving', 0.25, false),
  ('q48', 'mercy', 0.90, false),
  ('q49', 'teaching', 0.90, false),
  ('q50', 'prophecy', 0.75, true),
  ('q51', 'serving', 0.60, false),
  ('q51', 'mercy', 0.50, false),
  ('q52', 'encouragement', 0.90, false),
  ('q52', 'mercy', 0.25, false),
  ('q53', 'leadership', 0.55, false),
  ('q53', 'encouragement', 0.45, false),
  ('q53', 'giving', 0.25, false),
  ('q54', 'leadership', 0.55, false),
  ('q54', 'teaching', 0.35, false),
  ('q55', 'giving', 0.45, false),
  ('q55', 'serving', 0.45, false),
  ('q55', 'encouragement', 0.35, false),
  ('q56', 'prophecy', 0.25, false),
  ('q56', 'serving', 0.25, false),
  ('q56', 'mercy', 0.25, false),
  ('q56', 'leadership', 0.25, false)
on conflict (question_id, gift_id) do update set weight = excluded.weight, reverse_scored = excluded.reverse_scored;
